name: Download a file
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  testdler:
    runs-on: ubuntu-latest
    steps:
      - name: testdl
        run: curl https://viz.greynoise.io/api/v3/summary/tags?sort=created_at -o /gn.json
